 CREATE TABLE `User` (
    `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    `name` VARCHAR(99) NOT NULL,
    `pass` VARCHAR(99) NOT NULL,
    `isForbid` TINYINT DEFAULT 0 COMMENT "是否拉黑",
    `createdAt` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UNIQUE KEY `uniqName` (`name`)
) COMMENT "用户表";

CREATE TABLE `Post` (
    `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    `userId` BIGINT UNSIGNED NOT NULL,
    `title` VARCHAR(99) CHARACTER SET utf8mb4 NOT NULL,
    `description` VARCHAR(255),
    `content` TEXT CHARACTER SET utf8mb4 NOT NULL,
    `status` TINYINT DEFAULT 0 COMMENT "0 草稿 1 发布 2 下架",
    `createdAt` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `updatedAt` DATETIME NOT NULL,
    INDEX `idxUserId` (`userId`)
) COMMENT "文章表";